project_id = "auzbynhwadrrgbtxdrbs"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false
